# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgAttempts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11MsgAttempts.proto\x12\x07reactor\"$\n\x0bMsgAttempts\x12\x15\n\rnumOfAttempts\x18\x02 \x01(\x05\x62\x06proto3')



_MSGATTEMPTS = DESCRIPTOR.message_types_by_name['MsgAttempts']
MsgAttempts = _reflection.GeneratedProtocolMessageType('MsgAttempts', (_message.Message,), {
  'DESCRIPTOR' : _MSGATTEMPTS,
  '__module__' : 'MsgAttempts'
  # @@protoc_insertion_point(class_scope:reactor.MsgAttempts)
  })
_sym_db.RegisterMessage(MsgAttempts)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSGATTEMPTS._serialized_start=30
  _MSGATTEMPTS._serialized_end=66
# @@protoc_insertion_point(module_scope)
