# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReactorId.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fReactorId.proto\x12\x07reactor\"\x18\n\tReactorId\x12\x0b\n\x03rid\x18\x01 \x01(\x03\x62\x06proto3')



_REACTORID = DESCRIPTOR.message_types_by_name['ReactorId']
ReactorId = _reflection.GeneratedProtocolMessageType('ReactorId', (_message.Message,), {
  'DESCRIPTOR' : _REACTORID,
  '__module__' : 'ReactorId'
  # @@protoc_insertion_point(class_scope:reactor.ReactorId)
  })
_sym_db.RegisterMessage(ReactorId)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REACTORID._serialized_start=28
  _REACTORID._serialized_end=52
# @@protoc_insertion_point(module_scope)
